name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macos-latest
    name: SwiftLint
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Install Fastlane
      run: |
        gem install bundler
        bundle install
        
    - name: Run SwiftLint
      run: bundle exec fastlane lint_code

  build-and-test:
    runs-on: macos-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
      
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        
    - name: Run tests
      run: bundle exec fastlane tests